import { Poppins, Sora } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import SessionProviderWrapper from "@/components/components/sessionProviderWrappar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${sora.className} ${poppins.variable} antialiased`}>
        <SessionProviderWrapper>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
          {children}
        </ThemeProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
